=== Dev-Sites/Financial-Literacy/Micro5/vetadata-scorm-v1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--Conforms to w3c http://www.w3.org/2001/XMLSchema-->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.imsglobal.org/xsd/imsmd_rootv1p2p1" targetNamespace="http://www.imsglobal.org/xsd/imsmd_rootv1p2p1" elementFormDefault="qualified" version="1.2:1.1 IMS:MD1.2">
	<xsd:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="xml.xsd"/>
	<xsd:annotation>
		<xsd:documentation>This metadata Application Profile was developed for the Australian Vocational Training and Education (VTE) system.</xsd:documentation>
		<xsd:documentation>It was developed and is maintained by the E-standards for Training project of the Australian Flexible Learning Framework 2005-2006</xsd:documentation>
		<xsd:documentation>The profile is based on IMS LRM 1.2.4 (http://www.imsglobal.org/metadata/)</xsd:documentation>
		<xsd:documentation>This namespace used is consistent with IMS LRM 1.2.1 in order to conform to SCORM 1.2 conformance requirements</xsd:documentation>
		<xsd:documentation>Customised for Vetadata by Owen ONeill, June 2006</xsd:documentation>
		<xsd:documentation>Added a second optional location element for LORN, September 2006</xsd:documentation>
	</xsd:annotation>
	<xsd:group name="grp.any">
		<xsd:annotation>
			<xsd:documentation>Any namespaced element from any namespace may be used for an "any" element.  The namespace for the imported element must be defined in the instance, and the schema must be imported.  </xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:any namespace="##other" processContents="strict" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:group>
	<xsd:attributeGroup name="attr.type">
		<xsd:attribute name="type" default="URI">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="URI"/>
					<xsd:enumeration value="TEXT"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:attributeGroup>
	<xsd:attributeGroup name="attr.lornType">
		<xsd:attribute name="lornLocationType">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="download"/>
					<xsd:enumeration value="preview"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:attributeGroup>
	<!-- Copyright: 2005 (c) IMS Global Learning Consortium Inc.  All Rights Reserved.      -->
	<!-- IMS Global Learning Consortium, Inc. (IMS) is publishing the information contained -->
	<!-- in this binding (“Specification”) for purposes of scientific, experimental and     -->
	<!-- scholarly collaboration only.  IMS makes no warranty or representation regarding   -->
	<!-- the accuracy or completeness of the Specification.  This material is provided on   -->
	<!-- an “As Is” and “As Available” basis.  The Specification is at all times subject    -->
	<!-- to change and revision without notice.  It is your sole responsibility to evaluate -->
	<!-- the usefulness, accuracy and completeness of the Specification as it relates to    -->
	<!-- you.  IMS would appreciate receiving your comments and suggestions.  Please        -->
	<!-- contact IMS through our website at: http://www.imsglobal.org.                      -->
	<!-- ******************** -->
	<!-- ** Change History ** -->
	<!-- ******************** -->
	<!-- *************************** -->
	<!-- ** Attribute Declaration ** -->
	<!-- *************************** -->
	<!-- ************************* -->
	<!-- ** Element Declaration ** -->
	<!-- ************************* -->
	<xsd:element name="aggregationlevel" type="aggregationlevelType"/>
	<xsd:element name="annotation" type="annotationType"/>
	<xsd:element name="catalogentry" type="catalogentryType"/>
	<xsd:element name="catalog" type="catalogType"/>
	<xsd:element name="centity" type="centityType"/>
	<xsd:element name="classification" type="classificationType"/>
	<xsd:element name="context" type="contextType"/>
	<xsd:element name="contribute" type="contributeType"/>
	<xsd:element name="copyrightandotherrestrictions" type="copyrightandotherrestrictionsType"/>
	<xsd:element name="cost" type="costType"/>
	<xsd:element name="coverage" type="coverageType"/>
	<xsd:element name="date" type="dateType"/>
	<xsd:element name="datetime" type="datetimeType"/>
	<xsd:element name="description" type="descriptionType"/>
	<xsd:element name="difficulty" type="difficultyType"/>
	<xsd:element name="educational" type="educationalType"/>
	<xsd:element name="entry" type="entryType"/>
	<xsd:element name="format" type="formatType"/>
	<xsd:element name="general" type="generalType"/>
	<xsd:element name="identifier" type="xsd:string"/>
	<xsd:element name="intendedenduserrole" type="intendedenduserroleType"/>
	<xsd:element name="interactivitylevel" type="interactivitylevelType"/>
	<xsd:element name="interactivitytype" type="interactivitytypeType"/>
	<xsd:element name="keyword" type="keywordType"/>
	<xsd:element name="kind" type="kindType"/>
	<xsd:element name="langstring" type="langstringType"/>
	<xsd:element name="language" type="xsd:string"/>
	<xsd:element name="learningresourcetype" type="learningresourcetypeType"/>
	<xsd:element name="lifecycle" type="lifecycleType"/>
	<xsd:element name="location" type="locationType"/>
	<xsd:element name="lom" type="lomType"/>
	<xsd:element name="maximumversion" type="minimumversionType"/>
	<xsd:element name="metadatascheme" type="metadataschemeType"/>
	<xsd:element name="metametadata" type="metametadataType"/>
	<xsd:element name="minimumversion" type="maximumversionType"/>
	<xsd:element name="name" type="nameType"/>
	<xsd:element name="purpose" type="purposeType"/>
	<xsd:element name="relation" type="relationType"/>
	<xsd:element name="requirement" type="requirementType"/>
	<xsd:element name="resource" type="resourceType"/>
	<xsd:element name="rights" type="rightsType"/>
	<xsd:element name="role" type="roleType"/>
	<xsd:element name="semanticdensity" type="semanticdensityType"/>
	<xsd:element name="size" type="sizeType"/>
	<xsd:element name="source" type="sourceType"/>
	<xsd:element name="status" type="statusType"/>
	<xsd:element name="structure" type="structureType"/>
	<xsd:element name="taxon" type="taxonType"/>
	<xsd:element name="taxonpath" type="taxonpathType"/>
	<xsd:element name="technical" type="technicalType"/>
	<xsd:element name="title" type="titleType"/>
	<xsd:element name="type" type="typeType"/>
	<xsd:element name="typicalagerange" type="typicalagerangeType"/>
	<xsd:element name="typicallearningtime" type="typicallearningtimeType"/>
	<xsd:element name="value" type="valueType"/>
	<xsd:element name="person" type="personType"/>
	<xsd:element name="vcard" type="xsd:string"/>
	<xsd:element name="version" type="versionType"/>
	<xsd:element name="installationremarks" type="installationremarksType"/>
	<xsd:element name="otherplatformrequirements" type="otherplatformrequirementsType"/>
	<xsd:element name="duration" type="durationType"/>
	<xsd:element name="id" type="idType"/>
	<!-- ******************* -->
	<!-- ** Complex Types ** -->
	<!-- ******************* -->
	<xsd:complexType name="aggregationlevelType">
		<xsd:sequence>
			<xsd:element ref="source"/>
			<xsd:element ref="value"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="annotationType" mixed="true">
		<xsd:sequence>
			<xsd:element ref="person" minOccurs="0"/>
			<xsd:element ref="date" minOccurs="0"/>
			<xsd:element ref="description" minOccurs="0"/>
			<xsd:group ref="grp.any"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="catalogentryType" mixed="true">
		<xsd:sequence>
			<xsd:element ref="catalog" minOccurs="0"/>
			<xsd:element ref="entry" minOccurs="0"/>
			<xsd:group ref="grp.any"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="centityType">
		<xsd:sequence>
			<xsd:element ref="vcard"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="classificationType" mixed="true">
		<xsd:sequence>
			<xsd:element ref="purpose"/>
			<xsd:element ref="taxonpath" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="description"/>
			<xsd:element ref="keyword" maxOccurs="unbounded"/>
			<xsd:group ref="grp.any"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="contextType">
		<xsd:sequence>
			<xsd:element ref="source"/>
			<xsd:element ref="value"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="contributeType" mixed="true">
		<xsd:sequence>
			<xsd:element ref="role" minOccurs="0"/>
			<xsd:element ref="centity" maxOccurs="unbounded"/>
			<xsd:element ref="date"/>
			<xsd:group ref="grp.any"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="copyrightandotherrestrictionsType">
		<xsd:sequence>
			<xsd:element ref="source"/>
			<xsd:element ref="value"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="costType">
		<xsd:sequence>
			<xsd:element ref="source"/>
			<xsd:element ref="value"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="coverageType">
		<xsd:sequence>
			<xsd:element ref="langstring" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="dateType">
		<xsd:sequence>
			<xsd:element ref="datetime" minOccurs="0"/>
			<xsd:element ref="description" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="descriptionType">
		<xsd:sequence>
			<xsd:element ref="langstring" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="difficultyType">
		<xsd:sequence>
			<xsd:element ref="source"/>
			<xsd:element ref="value"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="durationType">
		<xsd:sequence>
			<xsd:element ref="datetime" minOccurs="0"/>
			<xsd:element ref="description" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="educationalType" mixed="true">
		<xsd:sequence>
			<xsd:element ref="interactivitytype" minOccurs="0"/>
			<xsd:element ref="learningresourcetype" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="interactivitylevel" minOccurs="0"/>
			<xsd:element ref="semanticdensity" minOccurs="0"/>
			<xsd:element ref="intendedenduserrole" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="context" maxOccurs="unbounded"/>
			<xsd:element ref="typicalagerange" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="difficulty" minOccurs="0"/>
			<xsd:element ref="typicallearningtime" minOccurs="0"/>
			<xsd:element ref="description" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="language" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:group ref="grp.any"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="entryType">
		<xsd:sequence>
			<xsd:element ref="langstring" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="generalType" mixed="true">
		<xsd:sequence>
			<xsd:element ref="identifier" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="title"/>
			<xsd:element ref="catalogentry" maxOccurs="unbounded"/>
			<xsd:element ref="language" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="description" maxOccurs="unbounded"/>
			<xsd:element ref="keyword" maxOccurs="unbounded"/>
			<xsd:element ref="coverage" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="structure" minOccurs="0"/>
			<xsd:element ref="aggregationlevel"/>
			<xsd:group ref="grp.any"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="installationremarksType">
		<xsd:sequence>
			<xsd:element ref="langstring" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="intendedenduserroleType">
		<xsd:sequence>
			<xsd:element ref="source"/>
			<xsd:element ref="value"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="interactivitylevelType">
		<xsd:sequence>
			<xsd:element ref="source"/>
			<xsd:element ref="value"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="interactivitytypeType">
		<xsd:sequence>
			<xsd:element ref="source"/>
			<xsd:element ref="value"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="keywordType">
		<xsd:sequence>
			<xsd:element ref="langstring" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="kindType">
		<xsd:sequence>
			<xsd:element ref="source"/>
			<xsd:element ref="value"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="langstringType">
		<xsd:simpleContent>
			<xsd:extension base="xsd:string">
				<xsd:attribute ref="xml:lang"/>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
	<xsd:complexType name="learningresourcetypeType">
		<xsd:sequence>
			<xsd:element ref="source"/>
			<xsd:element ref="value"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="lifecycleType" mixed="true">
		<xsd:sequence>
			<xsd:element ref="version"/>
			<xsd:element ref="status"/>
			<xsd:element ref="contribute" maxOccurs="unbounded"/>
			<xsd:group ref="grp.any"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="locationType">
		<xsd:simpleContent>
			<xsd:extension base="xsd:string">
				<xsd:attributeGroup ref="attr.lornType"/>
				<xsd:attributeGroup ref="attr.type"/>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
	<xsd:complexType name="lomType">
		<xsd:sequence>
			<xsd:element ref="general"/>
			<xsd:element ref="lifecycle"/>
			<xsd:element ref="metametadata"/>
			<xsd:element ref="technical"/>
			<xsd:element ref="educational" maxOccurs="unbounded"/>
			<xsd:element ref="rights"/>
			<xsd:element ref="relation" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="annotation" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="classification" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="metametadataType" mixed="true">
		<xsd:sequence>
			<xsd:element ref="identifier" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="catalogentry" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="contribute" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="metadatascheme" maxOccurs="unbounded"/>
			<xsd:element ref="language" minOccurs="0"/>
			<xsd:group ref="grp.any"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="nameType">
		<xsd:sequence>
			<xsd:element ref="source"/>
			<xsd:element ref="value"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="otherplatformrequirementsType">
		<xsd:sequence>
			<xsd:element ref="langstring" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="personType">
		<xsd:sequence>
			<xsd:element ref="vcard"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="purposeType">
		<xsd:sequence>
			<xsd:element ref="source"/>
			<xsd:element ref="value"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="relationType" mixed="true">
		<xsd:sequence>
			<xsd:element ref="kind" minOccurs="0"/>
			<xsd:element ref="resource" minOccurs="0"/>
			<xsd:group ref="grp.any"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="requirementType" mixed="true">
		<xsd:sequence>
			<xsd:element ref="type" minOccurs="0"/>
			<xsd:element ref="name" minOccurs="0"/>
			<xsd:element ref="minimumversion" minOccurs="0"/>
			<xsd:element ref="maximumversion" minOccurs="0"/>
			<xsd:group ref="grp.any"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="resourceType" mixed="true">
		<xsd:sequence>
			<xsd:element ref="identifier" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="description" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="catalogentry" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:group ref="grp.any"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="rightsType" mixed="true">
		<xsd:sequence>
			<xsd:element ref="cost"/>
			<xsd:element ref="copyrightandotherrestrictions"/>
			<xsd:element ref="description"/>
			<xsd:group ref="grp.any"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="roleType">
		<xsd:sequence>
			<xsd:element ref="source"/>
			<xsd:element ref="value"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="semanticdensityType">
		<xsd:sequence>
			<xsd:element ref="source"/>
			<xsd:element ref="value"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="sourceType">
		<xsd:sequence>
			<xsd:element ref="langstring"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="statusType">
		<xsd:sequence>
			<xsd:element ref="source"/>
			<xsd:element ref="value"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="stringType">
		<xsd:simpleContent>
			<xsd:extension base="xsd:string">
				<xsd:attribute ref="xml:lang"/>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
	<xsd:complexType name="structureType">
		<xsd:sequence>
			<xsd:element ref="source"/>
			<xsd:element ref="value"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="taxonpathType">
		<xsd:sequence>
			<xsd:element ref="source" minOccurs="0"/>
			<xsd:element ref="taxon" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="taxonType">
		<xsd:sequence>
			<xsd:element ref="id" minOccurs="0"/>
			<xsd:element ref="entry" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="technicalType" mixed="true">
		<xsd:sequence>
			<xsd:element ref="format" maxOccurs="unbounded"/>
			<xsd:element ref="size" minOccurs="0"/>
			<xsd:element ref="location" maxOccurs="3"/>
			<xsd:element ref="requirement" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="installationremarks" minOccurs="0"/>
			<xsd:element ref="otherplatformrequirements" minOccurs="0"/>
			<xsd:element ref="duration" minOccurs="0"/>
			<xsd:group ref="grp.any"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="titleType">
		<xsd:sequence>
			<xsd:element ref="langstring" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="typeType">
		<xsd:sequence>
			<xsd:element ref="source"/>
			<xsd:element ref="value"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="typicalagerangeType">
		<xsd:sequence>
			<xsd:element ref="langstring" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="typicallearningtimeType">
		<xsd:sequence>
			<xsd:element ref="datetime" minOccurs="0"/>
			<xsd:element ref="description" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="valueType">
		<xsd:sequence>
			<xsd:element ref="langstring"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="versionType">
		<xsd:sequence>
			<xsd:element ref="langstring" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<!-- ****************** -->
	<!-- ** Simple Types ** -->
	<!-- ****************** -->
	<xsd:simpleType name="formatType">
		<xsd:restriction base="xsd:string"/>
	</xsd:simpleType>
	<xsd:simpleType name="sizeType">
		<xsd:restriction base="xsd:int"/>
	</xsd:simpleType>
	<xsd:simpleType name="datetimeType">
		<xsd:restriction base="xsd:string"/>
	</xsd:simpleType>
	<xsd:simpleType name="idType">
		<xsd:restriction base="xsd:string"/>
	</xsd:simpleType>
	<xsd:simpleType name="metadataschemeType">
		<xsd:restriction base="xsd:string"/>
	</xsd:simpleType>
	<xsd:simpleType name="catalogType">
		<xsd:restriction base="xsd:string"/>
	</xsd:simpleType>
	<xsd:simpleType name="minimumversionType">
		<xsd:restriction base="xsd:string"/>
	</xsd:simpleType>
	<xsd:simpleType name="maximumversionType">
		<xsd:restriction base="xsd:string"/>
	</xsd:simpleType>
</xsd:schema>

=== Dev-Sites/Financial-Literacy/Micro5/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--This is a Reload version 2.5.1 Metadata document-->
<!--Spawned from the Reload Metadata Generator - http://www.reload.ac.uk-->
<lom xmlns="http://www.imsglobal.org/xsd/imsmd_rootv1p2p1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.imsglobal.org/xsd/imsmd_rootv1p2p1 http://e-standards.flexiblelearning.net.au/xsd/ims/vetadata-scorm-v1.xsd">
  <general>
    <title>
      <langstring xml:lang="en">Taxation requirements for the  business</langstring>
    </title>
    <catalogentry>
      <catalog>Australian Flexible Learning Toolboxes</catalog>
      <entry>
        <langstring xml:lang="en">1105_05</langstring>
      </entry>
    </catalogentry>
    <language>en-AU</language>
    <description>
      <langstring xml:lang="en">This learning object describes the performance outcomes, skills and knowledge required to outline the taxation requirements of a  business. It is applicable to many industry areas.</langstring>
    </description>
    <keyword>
      <langstring xml:lang="en">taxation acronyms</langstring>
    </keyword>
    <keyword>
      <langstring xml:lang="en">taxation requirements for a  business</langstring>
    </keyword>
    <keyword>
      <langstring xml:lang="en">tax file number registration</langstring>
    </keyword>
    <keyword>
      <langstring xml:lang="en">business activity statement</langstring>
    </keyword>
    <keyword>
      <langstring xml:lang="en">goods and services tax registration</langstring>
    </keyword>
    <keyword>
      <langstring xml:lang="en">Australian business number registration</langstring>
    </keyword>
    <keyword>
      <langstring xml:lang="en">pay as you go withholding registration</langstring>
    </keyword>
    <aggregationlevel>
      <source>
        <langstring xml:lang="x-none">LOMv1.0</langstring>
      </source>
      <value>
        <langstring xml:lang="x-none">3</langstring>
      </value>
    </aggregationlevel>
  </general>
  <lifecycle>
    <version>
      <langstring xml:lang="en">1.0</langstring>
    </version>
    <status>
      <source>
        <langstring xml:lang="x-none">LOMv1.0</langstring>
      </source>
      <value>
        <langstring xml:lang="x-none">final</langstring>
      </value>
    </status>
    <contribute>
      <role>
        <source>
          <langstring xml:lang="x-none">LOMv1.0</langstring>
        </source>
        <value>
          <langstring xml:lang="x-none">author</langstring>
        </value>
      </role>
      <centity>
        <vcard>Kangan Batman TAFE Melbourne Victoria</vcard>
      </centity>
      <date>
        <datetime>2008-12-15</datetime>
      </date>
    </contribute>
  </lifecycle>
  <metametadata>
    <metadatascheme>LOMv1.0</metadatascheme>
    <metadatascheme>VETADATAv0.1</metadatascheme>
  </metametadata>
  <technical>
    <format>text/html</format>
    <format>text/css</format>
    <format>image/jpeg</format>
    <format>image/gif</format>
    <format>application/x-shockwave-flash</format>
    <location type="URI">./</location>
  </technical>
  <educational>
    <learningresourcetype>
      <source>
        <langstring xml:lang="x-none">LOMv1.0</langstring>
      </source>
      <value>
        <langstring xml:lang="x-none">activity</langstring>
      </value>
    </learningresourcetype>
    <context>
      <source>
        <langstring xml:lang="x-none">LOMv1.0</langstring>
      </source>
      <value>
        <langstring xml:lang="x-none">training</langstring>
      </value>
    </context>
  </educational>
  <rights>
    <cost>
      <source>
        <langstring xml:lang="x-none">LOMv1.0</langstring>
      </source>
      <value>
        <langstring xml:lang="x-none">no</langstring>
      </value>
    </cost>
    <copyrightandotherrestrictions>
      <source>
        <langstring xml:lang="x-none">LOMv1.0</langstring>
      </source>
      <value>
        <langstring xml:lang="x-none">yes</langstring>
      </value>
    </copyrightandotherrestrictions>
    <description>
      <langstring xml:lang="en">TITLE: Licensed under Creative Commons Attribution-ShareAlike 3.0 Australia License; STATEMENT: This Learning Material may be freely used, copied, adapted and distributed. Limited warranty. Copyright in any enhancements vest automatically in the original copyright owner.; URL: http://creativecommons.org/licenses/by-sa/3.0/au; SPECIAL_CONDITIONS: The territory is limited to Australia and New Zealand only. You are not entitled to charge a fee for distribution or communication of the original Material, except as such Supply occurs in the context of education services provided by a Registered Training Organisation. Where you (the Licensee) Develop an Enhanced Version of the Material for commercial distribution, permission must be sought before enhancements are begun. If approval is provided, you must then provide a copy of the Enhanced Version and proposed pricing for the Enhanced Version to the Commonwealth at least twenty (20) Business Days prior to publication. Note: the above conditions do not restrict enhancement and use of the resource for educational purposes within your organisation, however you must provide a copy of the Enhanced Version to the Commonwealth prior to its use by your organisation.; COPYRIGHT_OWNER: Copyright is owned by the Commonwealth of Australia. This material may be freely used by Australian training organisations for educational purposes. Onselling of this material in any form requires agreement from eWorks, managing the copyright on behalf of the Commonwealth.  Distribution permissions, requests, notifications and copies of Enhanced Versions should be addressed  to eWorks, acting on behalf of the Flexible Learning Advisory Group Secretariat, National Advisory on Tertiary Education, Skills and Employment: eWorks' contact details are Level 5, 437 St Kilda Road, Melbourne, Victoria 3004 or email: enquiries@eworks.edu.au.;</langstring>
    </description>
  </rights>
  <classification>
    <purpose>
      <source>
        <langstring xml:lang="x-none">LOMv1.0</langstring>
      </source>
      <value>
        <langstring xml:lang="en">competency</langstring>
      </value>
    </purpose>
    <taxonpath>
      <source>
        <langstring xml:lang="x-none">http://www.ntis.gov.au</langstring>
      </source>
      <taxon>
        <id>BSBSMB305A</id>
        <entry>
          <langstring xml:lang="en">Comply with regulatory, taxation and insurance requirements for the  business</langstring>
        </entry>
      </taxon>
    </taxonpath>
    <description>
      <langstring xml:lang="en">BSBSMB305A Comply with regulatory, taxation and insurance requirements for the  business</langstring>
    </description>
    <keyword>
      <langstring xml:lang="en">BSBSMB305A Comply with regulatory, taxation and insurance requirements for the  business</langstring>
    </keyword>
  </classification>
  <classification>
    <purpose>
      <source>
        <langstring xml:lang="x-none">LOMv1.0</langstring>
      </source>
      <value>
        <langstring xml:lang="en">educational level</langstring>
      </value>
    </purpose>
    <taxonpath>
      <source>
        <langstring xml:lang="x-none">http://www.aqf.edu.au/thirteen.htm</langstring>
      </source>
      <taxon>
        <id />
        <entry>
          <langstring xml:lang="en">Certificate III</langstring>
        </entry>
      </taxon>
    </taxonpath>
    <description>
      <langstring xml:lang="en">Certificate III</langstring>
    </description>
    <keyword>
      <langstring xml:lang="en">Certificate III</langstring>
    </keyword>
  </classification>
</lom>
